apiVersion: v1
kind: Service
metadata:
  name: mongodb-service

spec:
  selector:
    app: mongodb

  ports:
  - port: {{ .Values.mongodb.servicePort }}
    targetPort: {{ .Values.mongodb.servicePort }}

  type: ClusterIP
